version: '2.4'

services:
  keycloak:
    image: jboss/keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data

  spo:
    build: 
      context: ./SPO-Simul
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 20s
      timeout: 7s
      retries: 7
    depends_on:
      - keycloak

  backend:
    build: 
      context: ./Server
    ports:
      - "5000:5000"
    depends_on:
      - spo
      - keycloak

  frontend:
    build: 
      context: ./front
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - keycloak

volumes:
  keycloak_data:
