version: '3'

services:
  backend:
    build: 
      context: ./Server
    ports:
      - "5000:5000"
    depends_on: 
      - frontend
  
  frontend:
    build: 
      context: ./front
    ports:
      - "3000:3000"
